# Generated by Django 3.2.4 on 2021-07-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210628_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Televisoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип матрицы')),
                ('display_freq', models.CharField(max_length=255, verbose_name='Частота дисплея')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('smart_fync', models.BooleanField(verbose_name='Наличие функции смарт')),
                ('display_3d_fync', models.BooleanField(verbose_name='Наличие функции 3D')),
                ('speaker_power', models.CharField(max_length=255, verbose_name='Мощность динамиков')),
                ('usb_qty', models.CharField(max_length=255, verbose_name='Количество USB портов')),
                ('hdmi_qty', models.CharField(max_length=255, verbose_name='Количество HDMI портов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
