# Generated by Django 3.2.4 on 2021-07-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210714_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bying_type',
            new_name='buying_type',
        ),
    ]
